# Generated by Django 5.2.17 on 2026-08-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fridge_photos/')),
                ('detected_ingredients', models.JSONField(blank=True, default=list, help_text='Liste [{"name": str, "expires_at": "YYYY-MM-DD"|null}] issue de YOLOv8.')),
                ('manual_ingredients', models.JSONField(blank=True, default=list, help_text='Même format que detected_ingredients, saisi manuellement en fallback.')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients_used', models.JSONField(blank=True, default=list)),
                ('ingredients_missing', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('raw_response', models.TextField(blank=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('total_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('nutrition_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='ai_engine.history')),
            ],
        ),
    ]
