# Generated by Django 6.0.8 on 2026-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
