# Generated by Django 6.0.8 on 2026-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_history_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='personalization_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
